version: "3.8"

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot:/etc/letsencrypt:ro
      - ./certbot/www:/var/www/certbot:ro

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: /bin/sh -c "trap exit TERM; while :; do sleep 6h & wait $!; certbot renew --webroot -w /var/www/certbot; done"

  certbot_init:
    image: certbot/certbot
    container_name: certbot_init
    depends_on:
      - nginx
    volumes:
      - ./data/certbot:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: sh -c "certbot certonly --webroot -w /var/www/certbot -d dopameme.n-e.kr -d www.dopameme.n-e.kr --non-interactive --agree-tos --email yun3.jo@gmail.com"
