services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certbot:/etc/letsencrypt:ro
      - ./certbot/www:/var/www/certbot:ro
    entrypoint: /bin/sh -c "
      mkdir -p /etc/nginx/sites-enabled &&
      ln -sf /etc/nginx/sites-available/dopameme.conf /etc/nginx/sites-enabled/dopameme.conf &&
      rm -f /etc/nginx/conf.d/default.conf &&
      nginx -g 'daemon off;'"

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: /bin/sh -c "trap exit TERM; while :; do sleep 6h & wait $$!; done"
    command: certbot renew --webroot -w /var/www/certbot

  certbot_init:
    image: certbot/certbot
    container_name: certbot_init
    depends_on:
      - nginx
    volumes:
      - ./certbot:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: /bin/sh -c "trap exit TERM; exec sh"
    command: certbot certonly --webroot -w /var/www/certbot -d dopameme.n-e.kr -d www.dopameme.n-e.kr --non-interactive --agree-tos --email yun3.jo@gmail.com
